---
# This Service is for allowing internal traffic to reach our postgres server
# allowing internal communication between postgres, result and worker app 
apiVersion: v1
kind: Service
metadata: 
  name: db # This name is used in the result and worker app, so we have to use this specific name
  labels: 
    name: postgres-service
    app: demo-voting-app
spec:
  type: ClusterIP # Internal service not going to be exposed to the outside network
  ports:
    - port: 5432
      targetPort: 5432
  selector: 
    name: postgres-pod
    app: demo-voting-app
# end of this file
...